
local ffi = require "ffi"

local demo_h = require "demo_h"
local format_value = demo_h.format_value

local botm_draw_menu = function(p_open)
    if ig.Begin("Demo: Callback GameEvent", p_open) then
        format_value("void __cdecl botm_game_event(GameEventInfo *info);", " ")
        ig.NewLine()
        if ig.TreeNode("Enum GameEvent") then
            format_value("\tGameEvent_PlayerMoveClick", GameEvent_PlayerMoveClick)
            format_value("\tGameEvent_PlayerReleaseMoveClick", GameEvent_PlayerReleaseMoveClick)
            format_value("\tGameEvent_PlayerMoveClick_MouseTriggered", GameEvent_PlayerMoveClick_MouseTriggered)
            format_value("\tGameEvent_PetMoveClick", GameEvent_PetMoveClick)
            format_value("\tGameEvent_PlayerAttackMove", GameEvent_PlayerAttackMove)
            format_value("\tGameEvent_PlayerAttackMoveClick", GameEvent_PlayerAttackMoveClick)
            format_value("\tGameEvent_PlayerAttackMoveClick_MouseTriggered", GameEvent_PlayerAttackMoveClick_MouseTriggered)
            format_value("\tGameEvent_PlayerAttackOnlyClick", GameEvent_PlayerAttackOnlyClick)
            format_value("\tGameEvent_PlayerStopPosition", GameEvent_PlayerStopPosition)
            format_value("\tGameEvent_PlayerHoldPosition", GameEvent_PlayerHoldPosition)
            format_value("\tGameEvent_NormalCastVisionItem", GameEvent_NormalCastVisionItem)
            format_value("\tGameEvent_SmartCastVisionItem", GameEvent_SmartCastVisionItem)
            format_value("\tGameEvent_SmartPlusSelfCastItem2", GameEvent_SmartPlusSelfCastItem2)
            format_value("\tGameEvent_SelfCastSpell4", GameEvent_SelfCastSpell4)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorItem2", GameEvent_SmartPlusSelfCastWithIndicatorItem2)
            format_value("\tGameEvent_SmartCastWithIndicatorItem2", GameEvent_SmartCastWithIndicatorItem2)
            format_value("\tGameEvent_SmartCastItem1", GameEvent_SmartCastItem1)
            format_value("\tGameEvent_UseItem6", GameEvent_UseItem6)
            format_value("\tGameEvent_SmartCastItem4", GameEvent_SmartCastItem4)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorItem1", GameEvent_SmartPlusSelfCastWithIndicatorItem1)
            format_value("\tGameEvent_UseItem5", GameEvent_UseItem5)
            format_value("\tGameEvent_SmartCastWithIndicatorItem6", GameEvent_SmartCastWithIndicatorItem6)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorVisionItem", GameEvent_SmartPlusSelfCastWithIndicatorVisionItem)
            format_value("\tGameEvent_UseItem1", GameEvent_UseItem1)
            format_value("\tGameEvent_CastSpell4", GameEvent_CastSpell4)
            format_value("\tGameEvent_CastSpell3", GameEvent_CastSpell3)
            format_value("\tGameEvent_CastSpell2", GameEvent_CastSpell2)
            format_value("\tGameEvent_SelfCastItem2", GameEvent_SelfCastItem2)
            format_value("\tGameEvent_CastSpell1", GameEvent_CastSpell1)
            format_value("\tGameEvent_CastAvatarSpell2", GameEvent_CastAvatarSpell2)
            format_value("\tGameEvent_CastAvatarSpell1", GameEvent_CastAvatarSpell1)
            format_value("\tGameEvent_NormalCastSpell4", GameEvent_NormalCastSpell4)
            format_value("\tGameEvent_NormalCastSpell3", GameEvent_NormalCastSpell3)
            format_value("\tGameEvent_NormalCastSpell2", GameEvent_NormalCastSpell2)
            format_value("\tGameEvent_NormalCastSpell1", GameEvent_NormalCastSpell1)
            format_value("\tGameEvent_NormalCastAvatarSpell2", GameEvent_NormalCastAvatarSpell2)
            format_value("\tGameEvent_NormalCastAvatarSpell1", GameEvent_NormalCastAvatarSpell1)
            format_value("\tGameEvent_SmartCastSpell4", GameEvent_SmartCastSpell4)
            format_value("\tGameEvent_SmartCastSpell3", GameEvent_SmartCastSpell3)
            format_value("\tGameEvent_UseItem3", GameEvent_UseItem3)
            format_value("\tGameEvent_SmartCastSpell2", GameEvent_SmartCastSpell2)
            format_value("\tGameEvent_SmartCastSpell1", GameEvent_SmartCastSpell1)
            format_value("\tGameEvent_SmartCastAvatarSpell2", GameEvent_SmartCastAvatarSpell2)
            format_value("\tGameEvent_SmartCastAvatarSpell1", GameEvent_SmartCastAvatarSpell1)
            format_value("\tGameEvent_SmartCastWithIndicatorSpell4", GameEvent_SmartCastWithIndicatorSpell4)
            format_value("\tGameEvent_SmartCastWithIndicatorSpell3", GameEvent_SmartCastWithIndicatorSpell3)
            format_value("\tGameEvent_SmartCastWithIndicatorSpell2", GameEvent_SmartCastWithIndicatorSpell2)
            format_value("\tGameEvent_SmartCastWithIndicatorSpell1", GameEvent_SmartCastWithIndicatorSpell1)
            format_value("\tGameEvent_SmartCastWithIndicatorAvatarSpell2", GameEvent_SmartCastWithIndicatorAvatarSpell2)
            format_value("\tGameEvent_SmartCastWithIndicatorAvatarSpell1", GameEvent_SmartCastWithIndicatorAvatarSpell1)
            format_value("\tGameEvent_SelfCastSpell3", GameEvent_SelfCastSpell3)
            format_value("\tGameEvent_SelfCastSpell2", GameEvent_SelfCastSpell2)
            format_value("\tGameEvent_SelfCastSpell1", GameEvent_SelfCastSpell1)
            format_value("\tGameEvent_NormalCastItem5", GameEvent_NormalCastItem5)
            format_value("\tGameEvent_SelfCastAvatarSpell2", GameEvent_SelfCastAvatarSpell2)
            format_value("\tGameEvent_SelfCastAvatarSpell1", GameEvent_SelfCastAvatarSpell1)
            format_value("\tGameEvent_SmartPlusSelfCastSpell4", GameEvent_SmartPlusSelfCastSpell4)
            format_value("\tGameEvent_SmartPlusSelfCastSpell3", GameEvent_SmartPlusSelfCastSpell3)
            format_value("\tGameEvent_SelfCastVisionItem", GameEvent_SelfCastVisionItem)
            format_value("\tGameEvent_SmartPlusSelfCastSpell2", GameEvent_SmartPlusSelfCastSpell2)
            format_value("\tGameEvent_SmartPlusSelfCastSpell1", GameEvent_SmartPlusSelfCastSpell1)
            format_value("\tGameEvent_SmartPlusSelfCastAvatarSpell2", GameEvent_SmartPlusSelfCastAvatarSpell2)
            format_value("\tGameEvent_SmartCastWithIndicatorItem3", GameEvent_SmartCastWithIndicatorItem3)
            format_value("\tGameEvent_SmartPlusSelfCastAvatarSpell1", GameEvent_SmartPlusSelfCastAvatarSpell1)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorSpell4", GameEvent_SmartPlusSelfCastWithIndicatorSpell4)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorSpell3", GameEvent_SmartPlusSelfCastWithIndicatorSpell3)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorSpell2", GameEvent_SmartPlusSelfCastWithIndicatorSpell2)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorSpell1", GameEvent_SmartPlusSelfCastWithIndicatorSpell1)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorAvatarSpell2", GameEvent_SmartPlusSelfCastWithIndicatorAvatarSpell2)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorAvatarSpell1", GameEvent_SmartPlusSelfCastWithIndicatorAvatarSpell1)
            format_value("\tGameEvent_UseItem7", GameEvent_UseItem7)
            format_value("\tGameEvent_UseVisionItem", GameEvent_UseVisionItem)
            format_value("\tGameEvent_UseItem4", GameEvent_UseItem4)
            format_value("\tGameEvent_UseItem2", GameEvent_UseItem2)
            format_value("\tGameEvent_NormalCastItem6", GameEvent_NormalCastItem6)
            format_value("\tGameEvent_NormalCastItem4", GameEvent_NormalCastItem4)
            format_value("\tGameEvent_NormalCastItem3", GameEvent_NormalCastItem3)
            format_value("\tGameEvent_NormalCastItem2", GameEvent_NormalCastItem2)
            format_value("\tGameEvent_NormalCastItem1", GameEvent_NormalCastItem1)
            format_value("\tGameEvent_SmartCastItem6", GameEvent_SmartCastItem6)
            format_value("\tGameEvent_SmartCastItem5", GameEvent_SmartCastItem5)
            format_value("\tGameEvent_SmartCastItem3", GameEvent_SmartCastItem3)
            format_value("\tGameEvent_SmartCastItem2", GameEvent_SmartCastItem2)
            format_value("\tGameEvent_SmartCastWithIndicatorVisionItem", GameEvent_SmartCastWithIndicatorVisionItem)
            format_value("\tGameEvent_SmartCastWithIndicatorItem5", GameEvent_SmartCastWithIndicatorItem5)
            format_value("\tGameEvent_SmartCastWithIndicatorItem4", GameEvent_SmartCastWithIndicatorItem4)
            format_value("\tGameEvent_SmartCastWithIndicatorItem1", GameEvent_SmartCastWithIndicatorItem1)
            format_value("\tGameEvent_SelfCastItem6", GameEvent_SelfCastItem6)
            format_value("\tGameEvent_SelfCastItem5", GameEvent_SelfCastItem5)
            format_value("\tGameEvent_SelfCastItem4", GameEvent_SelfCastItem4)
            format_value("\tGameEvent_SelfCastItem3", GameEvent_SelfCastItem3)
            format_value("\tGameEvent_SelfCastItem1", GameEvent_SelfCastItem1)
            format_value("\tGameEvent_SmartPlusSelfCastVisionItem", GameEvent_SmartPlusSelfCastVisionItem)
            format_value("\tGameEvent_SmartPlusSelfCastItem6", GameEvent_SmartPlusSelfCastItem6)
            format_value("\tGameEvent_SmartPlusSelfCastItem5", GameEvent_SmartPlusSelfCastItem5)
            format_value("\tGameEvent_SmartPlusSelfCastItem4", GameEvent_SmartPlusSelfCastItem4)
            format_value("\tGameEvent_SmartPlusSelfCastItem3", GameEvent_SmartPlusSelfCastItem3)
            format_value("\tGameEvent_SmartPlusSelfCastItem1", GameEvent_SmartPlusSelfCastItem1)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorItem6", GameEvent_SmartPlusSelfCastWithIndicatorItem6)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorItem5", GameEvent_SmartPlusSelfCastWithIndicatorItem5)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorItem4", GameEvent_SmartPlusSelfCastWithIndicatorItem4)
            format_value("\tGameEvent_SmartPlusSelfCastWithIndicatorItem3", GameEvent_SmartPlusSelfCastWithIndicatorItem3)
            ig.TreePop()
        end
        
        ig.NewLine()
        ig.TextWrapped("Callback function triggered on various game events")
        ig.NewLine()
        ig.Text("Example:")
        ig.NewLine()
        ig.PushStyleColor(ig.lib.ImGuiCol_Text, demo_h.col_text)
        ig.Text("botm.game_event = function(evt)")
        ig.Text("\tif evt.type == GameEvent_PlayerStopPosition then")
        ig.Text("\t\t--state, x, y fields may be altered to change event behavior")
        ig.Text("\t\t--block field may be set to true to block the game event from being called")
        ig.Text("\t\tprint(\"botm.game_event\", evt.state, evt.x, evt.y, evt.block)")
        ig.Text("\tend")
        ig.Text("end")
        ig.PopStyleColor(1)
        
    end
    ig.End()
end

local botm_game_event = function(evt)
    if evt.type == GameEvent_PlayerStopPosition then
        --state, x, y fields may be altered to change event behavior
        --block field may be set to true to block the game event from being called
        print("botm.game_event", evt.state, evt.x, evt.y, evt.block)
    end
end

return {
    botm_draw_menu = botm_draw_menu,
    botm_game_event = botm_game_event,
}